#+Author: Henry Davies
#+title: Dotfiles README
Files which end in the =org= file extension are orgmode literate configs, and do not contain the actual configuration files for a given program. Rather these orgmode files contain source code blocks which are tangled /(or pushed)/ to the proper configuration files on demand. 

To reduce confusion, the =org= files in each sub-directory have been named according to the program it relates to. 
For example:
- the Hyprland config is named: =hyprland.org=
- the Waybar config is named: =waybar.org=
  
One notable exception to this naming convention is, I have named my Emacs config ~README.org~ instead of ~Emacs.org~. The reason I have named the Emacs this way is because GitHub only automatically expands orgmode or markdown files if they are named README, and given the complexity of my Emacs config I wanted the orgmode document to auto expand for better readability.

* Setup Script
For those who want a more automated setup process for dotfiles in this repository, checkout my [[https://github.com/SeizeOP/scripts/blob/main/bash/setup.sh][Setup Script]].
